title: Black Trace
baseurl: "/black-trace-osint"
url: "https://cryogenized-spec.github.io"
markdown: kramdown
kramdown:
  toc_levels: 2..3
  parse_block_html: true
  
collections:
  cases:
    output: true
    permalink: /cases/:slug/
  briefs:
    output: true
    permalink: /briefs/:slug/

defaults:
  - scope:
      path: ""
      type: cases
    values:
      layout: case
  - scope:
      path: ""
      type: briefs
    values:
      layout: default

